### ISSUE TITLE
FastBoot error

### ISSUE THREAD

**Issue by locks** [johnotander/ember-remarkable#17]
I am getting the following error when trying to run https://github.com/locks/tombot-viewer under FastBoot:

```
fastboot-dist/fastboot/vendor.js:68542
  str = str.replace(SPACES_RE, ' ');
            ^
TypeError: str.replace is not a function
    at ParserBlock.parse (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/remarkable/dist/remarkable.js:3316:1)
    at Array.block (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/remarkable/dist/remarkable.js:5936:1)
    at Core.process (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/remarkable/dist/remarkable.js:3396:1)
    at Remarkable.parse (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/remarkable/dist/remarkable.js:3130:1)
    at Remarkable.render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/remarkable/dist/remarkable.js:3144:1)
    at [object Object].<anonymous> (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/ember-remarkable/components/md-text.js:31:1)
    at Descriptor.ComputedPropertyPrototype.get (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:14893:1)
    at Object.get (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:20290:1)
    at Object.exports.default._emberMetalStreamsStream.default.extend.compute (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:21438:1)
    at Object.BasicStream.value (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:21630:1)
    at Object.read (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:21997:1)
    at Object.getValue (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:8727:1)
    at Object.range (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47865:1)
    at Object.AlwaysDirtyVisitor.content (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48257:1)
    at RenderResult.populateNodes (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48655:1)
    at RenderResult.render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48588:1)
    at render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48398:1)
    at /Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49225:1
    at renderAndCleanup (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49260:1)
    at Block._firstRender (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49222:1)
    at Block.invoke (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49200:1)
    at yieldKeyword (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11004:1)
    at handleKeyword (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47577:1)
    at handleRedirect (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47563:1)
    at Object.inline (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47706:1)
    at Object.AlwaysDirtyVisitor.content (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48242:1)
    at RenderResult.populateNodes (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48655:1)
    at RenderResult.render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48588:1)
    at render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48398:1)
    at /Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49225:1
    at renderAndCleanup (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49260:1)
    at Block._firstRender (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49222:1)
    at Block.invoke (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49200:1)
    at ComponentNodeManager_render_instrument (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11288:1)
    at Object.instrument (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11999:1)
    at ComponentNodeManager_render [as render] (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11281:1)
    at Object.componentHook [as component] (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:8309:1)
    at handleRedirect (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47552:1)
    at Object.inline (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47706:1)
    at Object.AlwaysDirtyVisitor.inline (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48233:1)
    at RenderResult.populateNodes (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48653:1)
    at RenderResult.render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48588:1)
    at Object.render [as default] (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48398:1)
    at /Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47156:1
    at Object.yieldItem (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47263:1)
    at /Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:7666:1
    at Array.forEach (native)
    at forEach (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:7674:1)
    at Object.eachHelper [as helper] (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:7663:1)
    at Object._emberMetalStreamsStream.default.extend.compute (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11724:1)
    at Object.BasicStream.value (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:21630:1)
    at Object.invokeHelper (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:8790:1)
    at /Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47534:1
    at Object.renderAndCleanup (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49260:1)
    at hostBlock (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47540:1)
    at continueBlock (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47532:1)
    at Object.block (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47528:1)
    at Object.AlwaysDirtyVisitor.block (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48222:1)
    at RenderResult.populateNodes (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48651:1)
    at RenderResult.render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48588:1)
    at render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48398:1)
    at /Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49225:1
    at renderAndCleanup (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49260:1)
    at Block._firstRender (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49222:1)
    at Block.invoke (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49200:1)
    at yieldKeyword (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11004:1)
    at handleKeyword (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47577:1)
    at handleRedirect (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47563:1)
    at Object.inline (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47706:1)
    at Object.AlwaysDirtyVisitor.content (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48242:1)
    at RenderResult.populateNodes (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48655:1)
    at RenderResult.render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48588:1)
    at render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48398:1)
    at /Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49225:1
    at renderAndCleanup (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49260:1)
    at Block._firstRender (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49222:1)
    at Block.invoke (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49200:1)
    at yieldKeyword (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11004:1)
    at handleKeyword (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47577:1)
    at handleRedirect (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47563:1)
    at Object.inline (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47706:1)
    at Object.AlwaysDirtyVisitor.content (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48242:1)
    at RenderResult.populateNodes (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48655:1)
    at RenderResult.render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48588:1)
    at render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48398:1)
    at /Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49225:1
    at renderAndCleanup (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49260:1)
    at Block._firstRender (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49222:1)
    at Block.invoke (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49200:1)
    at ComponentNodeManager_render_instrument (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11288:1)
    at Object.instrument (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11999:1)
    at ComponentNodeManager_render [as render] (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11281:1)
    at Object.componentHook [as component] (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:8309:1)
    at handleRedirect (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47552:1)
    at Object.block (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47524:1)
    at Object.AlwaysDirtyVisitor.block (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48222:1)
    at RenderResult.populateNodes (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48651:1)
    at RenderResult.render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48588:1)
    at render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48398:1)
    at /Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49225:1
    at renderAndCleanup (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49260:1)
    at Block._firstRender (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49222:1)
    at Block.invoke (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49200:1)
    at yieldKeyword (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11004:1)
    at handleKeyword (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47577:1)
    at handleRedirect (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47563:1)
    at Object.inline (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47706:1)
    at Object.AlwaysDirtyVisitor.content (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48242:1)
    at RenderResult.populateNodes (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48655:1)
    at RenderResult.render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48588:1)
    at render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48398:1)
    at /Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49225:1
    at renderAndCleanup (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49260:1)
    at Block._firstRender (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49222:1)
    at Block.invoke (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49200:1)
    at ViewNodeManager_render_instrument (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11547:1)
    at Object.instrument (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11999:1)
    at ViewNodeManager_render [as render] (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11535:1)
    at Object.exports.default.render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:10280:1)
    at handleKeyword (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47616:1)
    at handleRedirect (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47563:1)
    at Object.inline (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:47706:1)
    at Object.AlwaysDirtyVisitor.content (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48242:1)
    at RenderResult.populateNodes (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48655:1)
    at RenderResult.render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48588:1)
    at render (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:48398:1)
    at /Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49225:1
    at renderAndCleanup (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49260:1)
    at Block._firstRender (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49222:1)
    at Block.invoke (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:49200:1)
    at ViewNodeManager_render_instrument (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11547:1)
    at Object.instrument (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11999:1)
    at ViewNodeManager_render [as render] (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:11535:1)
    at Object.renderHTMLBarsBlock (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:12223:1)
    at [object Object]._emberMetalMixin.Mixin.create.renderBlock (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:41491:1)
    at Renderer_prerenderTopLevelView [as prerenderTopLevelView] (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:23178:1)
    at Renderer_renderTopLevelView [as renderTopLevelView] (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:23187:1)
    at Queue.invoke (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:325:1)
    at Object.Queue.flush (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:391:1)
    at Object.DeferredActionQueues.flush (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:192:1)
    at Object.Backburner.end (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:570:1)
    at [object Object]._onTimeout (/Users/locks/src/tombot-viewer/fastboot-dist/fastboot/bower_components/ember/ember.debug.js:1161:1)
    at Timer.listOnTimeout (timers.js:92:15)
```

I'm not exactly sure how to dive more into it, so if you have some ideas please let me know :)

**Comment by johnotander** [comment]
Thanks for opening the issue! I'll do a bit of digging today and see if I can figure out what's going on.

**Comment by johnotander** [comment]
After a bit of digging, @locks, I couldn't seem to reproduce your issue. Do you have a branch that can reproduce this? I checked out the fastboot branch and was able to add back the `md-text` component and it didn't seem to error out when running `$ ember fastboot`.

Also, do you happen to know what input you gave the component to cause it to error? Looking at the stack trace it looks like you _may_ have found a bug in the Remarkable parser.

Thanks!

**Comment by locks** [comment]
Whoops, this one slipped by :x I no longer have access to the repository so we can call this dead. Thanks for the reply :) Happy 2018!
